#include <FastLED.h>

// Hardware definitions
#define LED_PIN     13
#define HALL_PIN    15
#define NUM_LEDS    116

// Safe brightness limit to prevent ESP32 power crashes
#define BRIGHTNESS  40

CRGB leds[NUM_LEDS];

// Volatile flag to safely communicate between the Interrupt and the main loop
volatile bool trigger_detected = false;

// Interrupt Service Routine (ISR)
void IRAM_ATTR hall_isr() {
  trigger_detected = true;
}

void setup() {
  // Initialize the Hall sensor pin
  pinMode(HALL_PIN, INPUT_PULLUP);
  
  // Attach the interrupt to trigger specifically on a RISING edge
  // (Signal going from LOW to HIGH)
  attachInterrupt(digitalPinToInterrupt(HALL_PIN), hall_isr, RISING);

  // Initialize the FastLED strip
  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);
  FastLED.setBrightness(BRIGHTNESS);
  
  // Ensure LEDs start completely off
  FastLED.clear();
  FastLED.show();
}

void loop() {
  if (trigger_detected) {
    // 1. Turn all LEDs ON (Solid Green)
    fill_solid(leds, NUM_LEDS, CRGB::Green);
    FastLED.show();

    // 2. Keep the LEDs on for a short period (50 milliseconds)
    delay(50);

    // 3. Turn all LEDs OFF
    FastLED.clear();
    FastLED.show();

    // 4. Reset the trigger flag AFTER the delay. 
    // This acts as a simple hardware debounce: any extra RISING edges 
    // generated by physical sensor bounce during the 50ms flash are safely ignored.
    trigger_detected = false;
  }
  
  // A tiny delay to keep the ESP32's background systems stable
  delay(1);
}